In [ ]:
# pip install opencv-python

In [1]:
import numpy as np
import cv2 as cv

In [3]:
import os

In [5]:
pwd

'C:\\Users\\Admin\\Star Agile\\Lecture Files-20250904\\DS-OSL Capstone Project 2025\\Real-time face detection- Cyber Security & Sentiment analysis- e-commerce'

In [13]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 8270-7EF8

 Directory of C:\Users\Admin\Star Agile\Lecture Files-20250904\DS-OSL Capstone Project 2025\Real-time face detection- Cyber Security & Sentiment analysis- e-commerce

10/30/2025  12:38 PM    <DIR>          .
10/30/2025  12:28 PM    <DIR>          ..
10/30/2025  12:31 PM    <DIR>          .ipynb_checkpoints
10/30/2025  12:37 PM             5,226 Capstones Projects-2 face detection.ipynb
10/30/2025  12:38 PM           140,321 image1.jpg
10/30/2025  12:38 PM           301,272 image2.jpg
10/30/2025  12:38 PM           228,094 image3.jpg
               4 File(s)        674,913 bytes
               3 Dir(s)  318,329,372,672 bytes free


In [32]:
os.listdir()

['.ipynb_checkpoints',
 'Capstones Projects-2 face detection.ipynb',
 'image1.jpg',
 'image2.jpg',
 'image3.jpg']

### Reading and Displaying the Image

In [21]:
# Reading and Displaying the Image one
image_1 = cv.imread("image1.jpg")
cv.imshow("This is The First Image", image_1)
cv.waitKey(0)
cv.destroyAllWindows()

In [28]:
# Reading and Displaying the second image
image_2 = cv.imread("image2.jpg")
cv.imshow("This Is The Secend Image", image_2)
cv.waitKey(0)
cv.destroyAllWindows()

In [30]:
# reading and Displaying the Third Image
image_3 = cv.imread("image3.jpg")
cv.imshow("This is The Third Image", image_3)
cv.waitKey(0)
cv.destroyAllWindows()

### Playing The Videos

In [21]:
# Playing the fist video 
video_1 = cv.VideoCapture("video1.mp4")
while True :
    _, frame = video_1.read()
    if not _:
        break
    cv.imshow("This is the my first video", frame)
    if cv.waitKey(20) & 0xFF == ord("q"):
        break

video_1.release()
cv.destroyAllWindows()

In [ ]:
import cv2 as cv

# Open the video file
video_1 = cv.VideoCapture("video1.mp4")

# Loop to read frames from the video
while True:
    # Read a single frame
    _, frame = video_1.read()

    # If the frame was not read successfully, the video has ended
    if not _:
        break

    # Display the frame in a window
    cv.imshow("This is my first video", frame)

    # Wait for a key press for 20 milliseconds
    # If the 'q' key is pressed, break the loop
    if cv.waitKey(20) & 0xFF == ord("q"):
        break

# Release the video capture object
video_1.release()

# Close all OpenCV windows
cv.destroyAllWindows()


In [9]:
# Playing the Second video
video_2 = cv.VideoCapture("video3.mp4")

while True:
    flag, frame = video_2.read()
    if not flag:
        break
    cv.imshow("This is the my second video", frame)
    if cv.waitKey(20) & 0xFF == ord("q"):
        break

video_2.release()
cv.destroyAllWindows()

### Putting the Shape on the image 

#### Putting the circle shape on the image

In [13]:
help(cv.circle)

Help on built-in function circle:

circle(...)
    circle(img, center, radius, color[, thickness[, lineType[, shift]]]) -> img
    .   @brief Draws a circle.
    .
    .   The function cv::circle draws a simple or filled circle with a given center and radius.
    .   @param img Image where the circle is drawn.
    .   @param center Center of the circle.
    .   @param radius Radius of the circle.
    .   @param color Circle color.
    .   @param thickness Thickness of the circle outline, if positive. Negative values, like #FILLED,
    .   mean that a filled circle is to be drawn.
    .   @param lineType Type of the circle boundary. See #LineTypes
    .   @param shift Number of fractional bits in the coordinates of the center and in the radius value.



In [55]:
my_image = cv.imread("ball.png")
cv.circle(my_image, (480, 700), 130, (0,255,0), thickness = 7)
cv.imshow("Putting the circle on the object ", my_image)
cv.waitKey(0)
cv.destroyAllWindows()

#### putting the Rectangle shape on the Image

In [62]:
#help(cv.rectangle)

In [136]:
my_image_1 = cv.imread("image1.jpg")
cv.rectangle(my_image_1, (550,150), (850,500), (0,255,0), thickness = 6)
cv.imshow("Putting the Rectangle Shape on the object", my_image_1)
cv.waitKey(0)
cv.destroyAllWindows()

### Face Detection in an image

In [18]:
image = cv.imread("sagar photo.jpg")
cv.imshow("This is the my Photo", image)
cv.waitKey(0)
cv.destroyAllWindows()

In [9]:
face_detect = cv.CascadeClassifier(cv.data.haarcascades + "haarcascade_frontalface_default.xml")

In [28]:
type(face_detect)

cv2.CascadeClassifier

In [38]:
help(face_detect.detectMultiScale)

Help on built-in function detectMultiScale:

detectMultiScale(...) method of cv2.CascadeClassifier instance
    detectMultiScale(image[, scaleFactor[, minNeighbors[, flags[, minSize[, maxSize]]]]]) -> objects
    .   @brief Detects objects of different sizes in the input image. The detected objects are returned as a list
    .       of rectangles.
    .
    .       @param image Matrix of the type CV_8U containing an image where objects are detected.
    .       @param objects Vector of rectangles where each rectangle contains the detected object, the
    .       rectangles may be partially outside the original image.
    .       @param scaleFactor Parameter specifying how much the image size is reduced at each image scale.
    .       @param minNeighbors Parameter specifying how many neighbors each candidate rectangle should have
    .       to retain it.
    .       @param flags Parameter with the same meaning for an old cascade as in the function
    .       cvHaarDetectObjects. It i

In [44]:
face_coords = face_detect.detectMultiScale(image, scaleFactor = 1.1, minNeighbors = 5, minSize = (40,40))
face_coords

array([[122, 121, 211, 211]], dtype=int32)

In [50]:
image = cv.imread("sagar photo.jpg")
cv.rectangle(image, (122, 121), (122+211, 121+211), (0,255,0), thickness = 3)
cv.imshow("Face detection", image)
cv.waitKey(0)
cv.destroyAllWindows()

In [62]:
face = cv.imread("Screenshot 2025-10-30 142048.png")
cv.imshow("This is the my Bike Delivry", face)
cv.waitKey(0)
cv.destroyAllWindows()

In [64]:
face_coords1 = face_detect.detectMultiScale(face, scaleFactor = 1.1, minNeighbors = 5, minSize = (40,40))
face_coords1

array([[ 90, 591, 230, 230],
       [513, 593, 222, 222],
       [ 65, 122, 275, 275],
       [486, 128, 264, 264]], dtype=int32)

In [70]:
face = cv.imread("Screenshot 2025-10-30 142048.png")
cv.rectangle(face, (65, 122), (65+275, 122+275), (0,255,0), thickness = 3)
cv.imshow("This is the my Bike Delivry", face)
cv.waitKey(0)
cv.destroyAllWindows()

## multiple face detection in a image

In [93]:
face = cv.imread("Screenshot 2025-10-30 184307.png")
cv.imshow("This is the my Bike Delivry", face)
cv.waitKey(0)
cv.destroyAllWindows()

In [95]:
faces_1_grayscale = cv.cvtColor(face, cv.COLOR_BGR2GRAY)
cv.imshow('image', faces_1_grayscale)
cv.waitKey(0)
cv.destroyAllWindows()

In [115]:
face_coords1 = face_detect.detectMultiScale(faces_1_grayscale, scaleFactor = 1.01, minNeighbors = 4, minSize = (30,30))
face_coords1

array([[261,  65,  32,  32],
       [ 44,  30,  32,  32],
       [324,  32,  31,  31],
       [199,  71,  40,  40],
       [ 96,  32,  32,  32],
       [328,  66,  49,  49],
       [166, 119,  50,  50],
       [136, 157,  50,  50],
       [282,  42,  31,  31],
       [180, 246,  63,  63]], dtype=int32)

In [116]:
face = cv.imread("Screenshot 2025-10-30 184307.png")
for x,y,w,h in face_coords1:
    cv.rectangle(face, (x,y), (x+w, y+h), (0,255,0), thickness = 4)
cv.imshow("This is the my Bike Delivry", face)
cv.waitKey(0)
cv.destroyAllWindows()

### Face detection by using the web camera

In [126]:
webcam = cv. VideoCapture(0)
cam_status, img = webcam.read()
print("Frame captured successfully:", cam_status)
webcam.release()

Frame captured successfully: True


In [132]:
face_detect = cv.CascadeClassifier(cv.data.haarcascades + "haarcascade_frontalface_default.xml")

In [140]:
def detect_faces():
    webcam = cv.VideoCapture(0)
    while True:
        _, frame = webcam.read()
        gray_frame = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
        faces = face_detect.detectMultiScale(gray_frame, scaleFactor=1.3, minNeighbors=5)
        for (x, y, w, h) in faces:
            cv.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv.imshow('Face Detection', frame)
        if cv.waitKey(1) & 0xFF == ord('q'):
            break
    webcam.release()
    cv.destroyAllWindows()


In [ ]:
detect_faces()

In [138]:
webcam.release()